version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - webnet

networks:
  webnet:
